name: 'Custom PR Merge Message'
description: 'Allows for custom PR merge messages'
inputs:
  github-token:
    description: "Github Token"
    required: true
  trigger-phrase:
    description: "Phrase that will trigger the merge"
    required: false
    default: "#merge"
  action:
    description: "Phrase that will trigger the merge"
    required: false
    default: merge
outputs:
  merged:
    description: "Boolean for whether it was merged or not"

runs:
  using: 'node16'
  main: 'index.js'